# Generated by Django 5.2.8 on 2025-11-25 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_client_contact_person_remove_client_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_name",
                    models.CharField(max_length=100, verbose_name="Grade Name"),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Base Salary"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Staff Grade",
                "verbose_name_plural": "Staff Grades",
                "ordering": ["grade_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Campaign Title"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "planned_start_date",
                    models.DateField(verbose_name="Planned Start Date"),
                ),
                ("planned_end_date", models.DateField(verbose_name="Planned End Date")),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Start Date"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual End Date"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Estimated Cost"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Budget"
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Actual Cost",
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(default=0, verbose_name="Completion %"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="PLANNING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="api.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Advert Title"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("IN_PRODUCTION", "In Production"),
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PLANNING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "production_progress",
                    models.IntegerField(
                        default=0, verbose_name="Production Progress %"
                    ),
                ),
                (
                    "scheduled_start_date",
                    models.DateField(verbose_name="Scheduled Start Date"),
                ),
                (
                    "scheduled_end_date",
                    models.DateField(verbose_name="Scheduled End Date"),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Start Date"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual End Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adverts",
                        to="api.campaign",
                        verbose_name="Campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Payment Amount"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="api.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[("CREATIVE", "Creative"), ("ADMIN", "Administrative")],
                        max_length=10,
                        verbose_name="Staff Type",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Hire Date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.staffgrade",
                        verbose_name="Grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
                "ordering": ["user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClientStaffContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Contact"),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_contacts",
                        to="api.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.staff",
                        verbose_name="Staff Contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Staff Contact",
                "verbose_name_plural": "Client Staff Contacts",
                "ordering": ["-is_primary", "-assigned_date"],
                "unique_together": {("client", "staff")},
            },
        ),
        migrations.CreateModel(
            name="CampaignStaffAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(max_length=100, verbose_name="Role on Campaign"),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="api.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.staff",
                        verbose_name="Staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Staff Assignment",
                "verbose_name_plural": "Campaign Staff Assignments",
                "ordering": ["-assigned_date"],
                "unique_together": {("campaign", "staff")},
            },
        ),
    ]
