# Generated by Django 5.2.8 on 2025-12-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_staffgrade_alter_client_options_campaign_advert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="banner_html",
            field=models.TextField(
                blank=True, null=True, verbose_name="Generated Banner HTML"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="banner_image_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Banner Image URL"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="banner_prompt",
            field=models.TextField(
                blank=True, null=True, verbose_name="Banner Generation Prompt"
            ),
        ),
    ]
