# Generated by Django 5.2.8 on 2025-12-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_campaign_banner_html_campaign_banner_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="banner_html",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="banner_image_url",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="banner_prompt",
        ),
        migrations.AddField(
            model_name="advert",
            name="banner_image_base64",
            field=models.TextField(
                blank=True, null=True, verbose_name="Banner Image Base64"
            ),
        ),
        migrations.AddField(
            model_name="advert",
            name="banner_image_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Banner Image URL"
            ),
        ),
        migrations.AddField(
            model_name="advert",
            name="banner_prompt",
            field=models.TextField(
                blank=True, null=True, verbose_name="AI Prompt Used"
            ),
        ),
        migrations.AddField(
            model_name="advert",
            name="banner_style",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Banner Style"
            ),
        ),
    ]
