# Generated by Django 5.2.8 on 2025-12-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_campaign_banner_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="banner_html",
            field=models.TextField(
                blank=True, null=True, verbose_name="Banner HTML Fallback"
            ),
        ),
    ]
